site_name: Aeon Documentation
nav:
  - Introduction: 'index.md'
  - Tutorial:
    - Getting started: 'tutorial/getting-started.md'
    - Basic examples: 'tutorial/basic-examples.md'
    - FAQ: 'tutorial/faq.md'
  - Documentation:
    - aeond:
      - Options: 'documentation/aeond/options.md'
      - Commands: 'documentation/aeond/commands.md'
    - Wallet CLI: 
      - Options: 'documentation/wallet-cli/options.md'
      - Commands: 'documentation/wallet-cli/commands.md'
    - Wallet RPC: 
      - Options: 'documentation/wallet-rpc/options.md'
      - Commands: 'documentation/wallet-rpc/commands.md'
  - The project:
    - Bug report: 'the-project/bug-report.md'
    - Charts: 
      - Block Count:
        - Daily: 'the-project/charts/block_count_24h.md'
        - Total: 'the-project/charts/block_height.md'
      - Block Difficulty: 'the-project/charts/block_difficulty.md'
      - Block Reward: 'the-project/charts/block_reward.md'
      - Block Size: 
        - Median: 'the-project/charts/block_size_median_24h.md'
        - Total: 'the-project/charts/block_size_cum.md'
      - Block Time: 'the-project/charts/block_time_median_24h.md'
      - Fees:
        - AEON: 'the-project/charts/fee_24h.md'
        - USD: 'the-project/charts/fee_24h_usd.md'
      - Inflation: 'the-project/charts/inflation_1Y.md'
      - Marketcap:
        - USD: 'the-project/charts/marketcap.md'
        - BTC: 'the-project/charts/marketcap_btc.md'
        - XMR: 'the-project/charts/marketcap_xmr.md'
      - Miner Revenue:
        - Daily: 'the-project/charts/miner_revenue_24h.md'
        - Yearly: 'the-project/charts/miner_revenue_1Y.md'
      - Nonces:
        - Values: 'the-project/charts/nonce.md'
        - Randomness: 'the-project/charts/nonce_dist.md'
      - Price:
        - BTC: 'the-project/charts/price_btc.md'
        - USD: 'the-project/charts/price.md'
        - XMR: 'the-project/charts/price_xmr.md'
      - Supply:
        - Circulating: 'the-project/charts/supply_total.md'
        - Locked: 'the-project/charts/supply_locked.md'
      - Transaction Volume: 
        - AEON: 'the-project/charts/volume.md'
        - BTC: 'the-project/charts/volume_btc.md'
        - USD: 'the-project/charts/volume_usd.md'
      - Transaction Signatures: 
        - Inputs: 'the-project/charts/inputs.md'
        - Outputs: 'the-project/charts/outputs.md'
        - Outputs-Inputs: 'the-project/charts/outputs_inputs.md'
      - Transactions:
        - Daily: 'the-project/charts/tx_24h.md'
      - Version: 'the-project/charts/version.md'
    - Code of conduct: 'the-project/code-of-conduct.md'
    - Dependencies: 'the-project/dependencies.md'
    - Donate: 'the-project/donate.md'
    - Features: 'the-project/features.md'
    - History: 'the-project/history.md'
    - Install: 'the-project/install.md'
    - Known bugs: 'the-project/known-bugs.md'
    - TODO: 'the-project/todo.md'
    - Website info: 'the-project/web-site-info.md'
  - Releases:
    - Chronos: 'releases/chronos.md'
  - Who and why:
    - Companies: 'who-and-why/companies.md'
    - Copyright: 'who-and-why/copyright.md'
    - Sponsors: 'who-and-why/sponsors.md'
    - Thanks: 'who-and-why/thanks.md'
    - The name: 'who-and-why/the-name.md'
theme: 
  logo: img.svg
  palette:
    scheme: default
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu Mono
    code: Courier
markdown_extensions:
  - attr_list
extra_css:
  - extra.css