site_name: aeon.wiki
nav:
  - Introduction: 'index.md'
  - Tutorial:
    - Getting started: 'tutorial/getting-started.md'
    - Basic examples: 'tutorial/basic-examples.md'
    - Mining: 'tutorial/mining.md'
    - FAQ: 'tutorial/faq.md'
  - Documentation:
    - aeond:
      - Options: 'documentation/aeond/options.md'
      - Commands: 'documentation/aeond/commands.md'
    - Wallet CLI: 
      - Options: 'documentation/wallet-cli/options.md'
      - Commands: 'documentation/wallet-cli/commands.md'
    - Wallet RPC: 
      - Options: 'documentation/wallet-rpc/options.md'
      - Commands: 'documentation/wallet-rpc/commands.md'
  - The project:
    - Bug report: 'the-project/bug-report.md'
    - Code of conduct: 'the-project/code-of-conduct.md'
    - Contributing: 'the-project/contributing-guidelines.md'
    - Dependencies: 'the-project/dependencies.md'
    - Donate: 'the-project/donate.md'
    - Features: 'the-project/features.md'
    - History: 'the-project/history.md'
    - Install: 'the-project/install.md'
    - Known bugs: 'the-project/known-bugs.md'
    - Releases: 'the-project/releases.md'
    - TODO: 'the-project/todo.md'
  - Network info: 
    - Block explorer: 'https://explorer.aeon.wiki'
    - Charts: 
      - Blocks:
          - Count:
            - Daily: 'network-info/charts/block_count_24h.md'
            - Total: 'network-info/charts/block_height.md'
          - Reward: 'network-info/charts/block_reward.md'
          - Size: 
            - Monthly: 'network-info/charts/block_size.md'
            - Total: 'network-info/charts/block_size_cum.md'
      - Difficulty: 'network-info/charts/block_difficulty.md'
      - Inflation: 'network-info/charts/inflation_1Y.md'
      - Marketcap:
        - USD: 'network-info/charts/marketcap.md'
        - BTC: 'network-info/charts/marketcap_btc.md'
        - XMR: 'network-info/charts/marketcap_xmr.md'
      - Miner Revenue: 'network-info/charts/miner_revenue.md'
      - Nonces:
        - Values: 'network-info/charts/nonce.md'
        - Randomness: 'network-info/charts/nonce_dist.md'
        - Recent Values: 'network-info/charts/nonce_recent.md'
      - Price:
        - BTC: 'network-info/charts/price_btc.md'
        - USD: 'network-info/charts/price.md'
        - XMR: 'network-info/charts/price_xmr.md'
      - Supply:
        - Circulating: 'network-info/charts/supply_circulating.md'
        - Locked: 'network-info/charts/supply_locked.md'
        - Total: 'network-info/charts/supply_total.md'
      - Transactions:
          - Count: 'network-info/charts/tx.md'
          - Fees:
            - AEON: 'network-info/charts/fee.md'
            - USD: 'network-info/charts/fee_usd.md'
          - Volume: 
            - AEON: 'network-info/charts/volume.md'
            - BTC: 'network-info/charts/volume_btc.md'
            - USD: 'network-info/charts/volume_usd.md'
          - Inputs/Outputs: 
            - Inputs: 'network-info/charts/inputs.md'
            - Outputs: 'network-info/charts/outputs.md'
            - Outputs-Inputs: 'network-info/charts/outputs_inputs.md'
      - Version: 'network-info/charts/version.md'
    - Open Nodes: 'network-info/open-nodes.md'
  - Who and why:
    - Contributors: 'https://github.com/aeonix/aeon/graphs/contributors'
    - Copyright: 'who-and-why/copyright.md'
    - Sponsors: 'who-and-why/sponsors.md'
    - Thanks: 'who-and-why/thanks.md'
    - The name: 'who-and-why/the-name.md'
theme: 
  logo: ae-coin.svg
  favicon: ae-coin.png
  palette:
    scheme: default
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu Mono
    code: Courier
extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/AeonCommunity
          name: \@AeonCommunity
        - icon: fontawesome/brands/medium
          link: https://aeon-community.medium.com
          name: AEON Community
        - icon: fontawesome/brands/github
          link: https://github.com/aeonix/aeon
          name: Source Code
markdown_extensions:
  - attr_list
copyright: Copyright 2020 aeon.wiki. <br> Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. <br>You may obtain a copy of the License at <a href="http://www.apache.org/licenses/LICENSE-2.0">apache.org</a>
extra_css:
  - extra.css
