definitions = {
    'block_count_24h': {
        'title' : 'Block Count (Previous 24h)',
        'file-name' : 'block_count_24h',
        'x-axis' : 'date',
        'y-axis' : 'Blocks',
        'lineWidth' : '1',
        'logScale' : 'true',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'block_difficulty': {
        'title' : 'Network Difficulty',
        'file-name' : 'block_difficulty',
        'x-axis' : 'Date',
        'y-axis' : 'Hashes/Block',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'block_height': {
        'title' : 'Block Height',
        'file-name' : 'block_height',
        'x-axis' : 'Date',
        'y-axis' : 'Blocks',
        'logScale' : 'none',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'block_reward': {
        'title' : "Miner's Block Reward (Per Block)",
        'file-name' : 'block_reward',
        'x-axis' : 'Date',
        'y-axis' : 'æ',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'block_size_cum': {
        'title' : 'Blockchain Size',
        'file-name' : 'block_size_cum',
        'x-axis' : 'Date',
        'y-axis' : 'b',
        'logScale' : 'none',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'block_size_median_24h': {
        'title' : 'Block Size 24h Median',
        'file-name' : 'block_size_median_24h',
        'x-axis' : 'Date',
        'y-axis' : 'b',
        'logScale' : 'true',
        'curveType' : 'none',
        'lineWidth' : '1',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'block_time_median_24h': {
        'title' : 'Block Time (median of 24h)',
        'file-name' : 'block_time_median_24h',
        'x-axis' : 'Date',
        'y-axis' : 'Seconds',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'none',
        'format' : '###.000',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'fee_24h': {
        'title' : 'Fee 24h',
        'file-name' : 'fee_24h',
        'x-axis' : 'Date',
        'y-axis' : 'æ',
        'lineWidth' : '1',
        'logScale' : 'true',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'fee_24h_usd': {
        'title' : 'Fee 24h $',
        'file-name' : 'fee_24h_usd',
        'x-axis' : 'Date',
        'y-axis' : '$',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'inflation_1Y': {
        'title' : 'Inflation Rate',
        'file-name' : 'inflation_1Y',
        'x-axis' : 'Date',
        'y-axis' : '% of Circulating Supply',
        'logScale' : 'none',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '###.000',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } ,
    'inputs': {
        'title' : 'Tx Inputs 24h',
        'file-name' : 'inputs',
        'x-axis' : 'Date',
        'y-axis' : '#',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '######',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'marketcap': {
        'title' : 'Value of Circulating Supply',
        'file-name' : 'marketcap',
        'x-axis' : 'Date',
        'y-axis' : '$',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'marketcap_btc': {
        'title' : 'Value of Circulating Supply (BTC)',
        'file-name' : 'marketcap_btc',
        'x-axis' : 'Date',
        'y-axis' : 'BTC',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'marketcap_xmr': {
        'title' : 'Value of Circulating Supply (XMR)',
        'file-name' : 'marketcap_xmr',
        'x-axis' : 'Date',
        'y-axis' : 'XMR',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'miner_revenue_1Y': {
        'title' : "1Y Miner's Revenue (365 Days' Emission + Fees)",
        'file-name' : 'miner_revenue_1Y',
        'x-axis' : 'Date',
        'y-axis' : '$',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'miner_revenue_24h': {
        'title' : "24h Miner's Revenue (24 Hours' Emission + Fees)",
        'file-name' : 'miner_revenue_24h',
        'x-axis' : 'Date',
        'y-axis' : '$',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } ,
    'nonce': {
        'title' : 'Nonces',
        'file-name' : 'nonce',
        'x-axis' : 'Date',
        'y-axis' : 'Nonce Value Normalized by Maximum Nonce Value',
        'logScale' : 'none',
        'lineWidth' : '0',
        'pointSize' : '0.05',
        'curveType' : 'none',
        'format' : '##.###',
        'type': 'number',
        'chartType': 'ScatterChart',
        'interval' : '50',
    } , 
    'nonce_dist': {
        'title' : 'Nonce Distribution as Compared to a Uniform Distribution',
        'file-name' : 'nonce_dist',
        'x-axis' : 'Date',
        'y-axis' : 'Uniformity',
        'lineWidth' : '1',
        'logScale' : 'none',
        'curveType' : 'function',
        'format' : '##.###',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'outputs': {
        'title' : 'Tx Outputs 24h',
        'file-name' : 'outputs',
        'x-axis' : 'Date',
        'y-axis' : '#',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '######',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'outputs_inputs': {
        'title' : 'Tx Outputs minus Inputs cumulative',
        'file-name' : 'outputs_inputs',
        'x-axis' : 'Date',
        'y-axis' : '#',
        'logScale' : 'none',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '######',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'price': {
        'title' : 'Price',
        'file-name' : 'price',
        'x-axis' : 'Date',
        'y-axis' : '$',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'price_btc': {
        'title' : 'Price (BTC)',
        'file-name' : 'price_btc',
        'x-axis' : 'Date',
        'y-axis' : 'BTC',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'price_xmr': {
        'title' : 'Price (XMR)',
        'file-name' : 'price_xmr',
        'x-axis' : 'Date',
        'y-axis' : 'XMR',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'supply_locked': {
        'title' : 'Locked Aeon',
        'file-name' : 'supply_locked',
        'x-axis' : 'Date',
        'y-axis' : 'æ',
        'logScale' : 'none',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '###.000',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } ,
    'supply_total': {
        'title' : 'Circulating Supply',
        'file-name' : 'supply_total',
        'x-axis' : 'Date',
        'y-axis' : 'æ',
        'logScale' : 'none',
        'lineWidth' : '1',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'tx_24h': {
        'title' : 'Transactions (Previous 24h)',
        'file-name' : 'tx_24h',
        'x-axis' : 'Date',
        'y-axis' : 'Transactions',
        'lineWidth' : '1',
        'logScale' : 'true',
        'curveType' : 'function',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'version': {
        'title' : 'Version',
        'file-name' : 'version',
        'x-axis' : 'Date',
        'y-axis' : '#',
        'logScale' : 'none',
        'curveType' : 'none',
        'lineWidth' : '1',
        'format' : '##.#',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'volume': {
        'title' : 'Transaction Output Volume',
        'file-name' : 'volume',
        'x-axis' : 'Date',
        'y-axis' : 'æ',
        'logScale' : 'none',
        'lineWidth' : '1',
        'curveType' : 'none',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'volume_usd': {
        'title' : 'Transaction Output Volume $',
        'file-name' : 'volume_usd',
        'x-axis' : 'Date',
        'y-axis' : '$',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'none',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
    'volume_btc': {
        'title' : 'Transaction Output Volume BTC',
        'file-name' : 'volume_btc',
        'x-axis' : 'Date',
        'y-axis' : 'BTC',
        'logScale' : 'true',
        'lineWidth' : '1',
        'curveType' : 'none',
        'format' : '0.000E+00',
        'type': 'number',
        'chartType': 'LineChart',
        'pointSize' : '0',
        'interval' : '100',
    } , 
}
















